### ISSUE TITLE
TESTING.MD not accessible via website

### ISSUE THREAD

**Issue by groovecoder** [mdn/discord#159]

**Comment by openjck** [comment]
**Steps to reproduce:**

1. Navigate to https://mdn-discord.herokuapp.com/
2. Click *TESTING.md*

**Expected result:**

Testing instructions load

**Actual result:**

404

**Comment by groovecoder** [comment]
I think we should replace this bug with a change to remove all of the website home page except the install, config, and a link to GitHub for this kind of stuff.

**Comment by openjck** [comment]
Definitely, those are the important pieces of content that we need to get across. Since those are also covered on GitHub itself, we could even consider temporarily redirecting to GitHub, at least until we have some different content to show.

Are we using Universal Analytics? If so, we could continue to track homepage visits before the redirection happens.

**Comment by groovecoder** [comment]
WONTFIX.
