### ISSUE TITLE
Add a link to GitHub project/issues in comment(s)

### ISSUE THREAD

**Issue by groovecoder** [mdn/discord#48]
To quickly get more feedback from users, we should link them straight to our issue tracker from the comments on their commits.

**Comment by openjck** [comment]
I think this is an interesting idea. It would make it much easier for users to submit feedback and would almost definitely encourage people to report problems that they wouldn't have reported otherwise.

I wonder if we could achieve the same goal while still maintaining a conservative attitude toward product direction. MDN might be an interesting case study. We have lots of feature requests, but could name the most important goals from memory: runnable code examples, easier editing, improved collaboration. Sometimes I worry that big lists distract us from what really matters.

Stephen King has [an interesting quote](https://www.youtube.com/watch?v=l8TkQvdJVbc#t=10m27s) about this sort of thing:

> A writer's notebook is the best way in the world to immortalize bad ideas... A good idea is one that sticks around.

Donald Norman also talks about this in *The Invisible Computer*:

> Don’t ask people what they want. Watch them and figure out their needs.... If you just follow what people ask for, you could end up making their lives even more complicated.

Maybe watching users would serve us better than putting out an open call for ideas.

Anyway, forgive the novel. I hope the length of this comment doesn't imply that I dislike the idea. I think their are advantages and disadvantages to the approach. I think we would benefit from considering both, and just wanted to capture my thoughts for now.

**Comment by darkwing** [comment]
Shout out to @openjck for turning a basic GitHub issue into a Stephen King quote opportunity.

**Comment by openjck** [comment]
I've continued to think about this. Hearing from users would be great. I really am wondering what they think. At the same time, I do worry about putting out an open call for features from early adopters and expert users. I'm going to say *not now* for now, but that doesn't prevent us from keeping this in mind for the future.
